import os,sys 
import time
print() 
print("Searching For Updations.....")
time.sleep(3)
print("Updating To Newer Version...")
print()
print("Wait for the updation")
print()
os.system("pkg upgrade")
print()
print("Removing older version of Blackpearl")
time.sleep(3)
os.system("rm -rf Blackpearl-framework")
os.system("rm -rf /data/data/com.termux/files/usr/bin/pearl")
print()
print("Installing newer version of Blackpearl")
time.sleep(2)
os.system("git clone https://github.com/ProfesssorCipher/Blackpearl-framework.git")
print()
os.system("cd ~/Blackpearl-framework;python install.py")
print("Updated and Installed")
